simple_blog_demo-master/config/routes.rb
SimpleBlog::Application.routes.draw do
  
  root 'posts#index'

  resources :posts, :only => [:index, :create] do
    resources :comments, :only => [:new, :create]
  end

  

  

end

simple_blog_demo-master/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author, :length => { maximum: 20 }
  validates :content, :length => { maximum: 400 } 

  belongs_to :post

end

simple_blog_demo-master/app/models/post.rb
class Post < ActiveRecord::Base

  validates :author, :length => { maximum: 20 }
  validates :content, :length => { maximum: 400 } 

  has_many :comments

end

simple_blog_demo-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

simple_blog_demo-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

simple_blog_demo-master/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(:created_at => :desc).includes(:comments)
    @post = Post.new #create(:author => "hahaha")
  end

  def create
    @post = Post.create(post_params)
    if @post
      redirect_to :root
    else
      render :index
    end
  end



  private

  # Whitelist those params!
  def post_params
    params.require(:post).permit(:author, :content)
  end

end

simple_blog_demo-master/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_blog_demo-master/app/helpers/comments_helper.rb
module CommentsHelper
end

simple_blog_demo-master/app/helpers/posts_helper.rb
module PostsHelper
end

simple_blog_demo-master/app/views/comments/_comment.html.erb
<% unless comment.new_record? %>
  <div class="comment">
    <p>
      <%= comment.content %>
    </p>
    <p class="comment-author">
      -- <%= comment.author %>
    </p>
  </div>
<% end %>

simple_blog_demo-master/app/views/comments/_new_comment_form.html.erb
<%= form_for comment, 
    :url => post_comments_path(comment.post.id),
    :html => { :class => "form-horizontal comment-form" } do |f| %>
  <div class="form-group">
    <%= f.label :author, "Your Name" %>
    <%= f.text_field :author, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "Your Comment" %>
    <%= f.text_area :content, :rows => 6, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Comment", :class => "btn btn-primary form-control" %>
  </div>
<% end %>

simple_blog_demo-master/app/views/comments/new.html.erb
<div class="row posts">
  
  <div class="col-sm-5 col-sm-offset-2">
    <h3>
      Your Selected Post
    </h3>
    <%= render @post %>
    <div class="home-link">
      <%= link_to "<< Go back to home page", root_url %>
    </div>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <h3>
      Create a Comment
    </h3>
    <div class="col-sm-12">
      <%= render :partial => "new_comment_form", 
            :locals => { :comment => @comment } %>
    </div>
  </div>

</div>

simple_blog_demo-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "shared/header" %>
    <%= yield %>
  </div>

</body>
</html>

simple_blog_demo-master/app/views/posts/_new_post_form.html.erb
<%= form_for post, 
    :html => { :class => "form-horizontal post-form" } do |f| %>
  <div class="form-group">
    <%= f.label :author, "Your Name" %>
    <%= f.text_field :author, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "Your Post" %>
    <%= f.text_area :content, :rows => 6, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Post", :class => "btn btn-primary form-control" %>
  </div>
<% end %>

simple_blog_demo-master/app/views/posts/_post.html.erb
<div class="row post">
  <div class="col-sm-12">
    <h4>
      By <%= post.author %>
    </h4>
    <h5>
      Posted on <%= post.created_at.strftime("%A %b %d, %Y") %>
    </h5>
    <p>
      <%= post.content %>
    </p>
    <% unless post.comments.empty? %>
      <div class="comments">
        <h5 class="comments-head">
          Comments:
        </h5>
          <%= render post.comments %>     
      </div>
    <% end %>

    <% if @comment.nil? %>
      <%= link_to "Leave a comment!", new_post_comment_path(post), :class => "leave-comment" %>      
    <% end %>
  </div>
</div>

simple_blog_demo-master/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

simple_blog_demo-master/app/views/posts/index.html.erb
<div class="row posts">
  
  <div class="col-sm-5 col-sm-offset-2">
    <h3>
      Latest Posts
    </h3>
    <%= render @posts %>
  </div>

  <div class="col-sm-3 col-sm-offset-1">
    <h3>
      Create a Post
    </h3>
    <div class="col-sm-12">
      <%= render :partial => "new_post_form", 
            :locals => { :post => @post } %>
    </div>
  </div>

</div>

simple_blog_demo-master/app/views/shared/_header.html.erb
<div class="row">
  <header>
    <h1>
      SimpleBlog
    </h1>
    <h2>
      The easiest way for groups to blog that there ever was.
    </h2>
  </header>
</div>